spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/attendance_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

openai:
  api-key: ${OPENAI_API_KEY}
  model: gpt-4o-mini

logging:
  level:
    com.attendance: DEBUG
    org.springframework: INFO 